"Ddoink
syntax on
set autoindent

"Display line number and offset for the sake of d-number-arrow
set number
set relativenumber
set nowrap

"Smack me when I'm too talkative
set colorcolumn=120

"Smack me when I crumble whitespace all over the place
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

set laststatus=2
set splitbelow
set splitright
set incsearch
